### PR TITLE
#149466929 Ft add fitbit support

### PR DESCRIPTION
**Pull request by EdwinKato**
## PR Status
**READY**

## Story ID
149466929

## Added Migrations
YES 

## Description
Addition of fitbit integration. Weights and activity data to be specific

## New Packages Added
mock
mock-requests

## Related PRs
None

## Todos
- [ ] Wait for travis to build

### CODE REVIEW

**Review by amwaleh — APPROVED** [review]

**Review by amwaleh — CHANGES_REQUESTED** [review]
solve merge conflict

**Comment by EdwinKato** [comment]
@amwaleh Merge conflict solved and travis is building

**Review by collin5 — APPROVED** [review]

**Comment by amwaleh** [comment]
@EdwinKato plse resolve the conflicts

**Comment by EdwinKato** [comment]
@amwaleh Conflict resolved

**Pull request merged**
